colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["blogs"]

disableImageOptimization = false
hotlinkFeatureImage = false

highlightCurrentMenuArea = true
smartTOC = true

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "page"
  showRecent = false
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "blogs"
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showHero = true
  heroStyle = "basic"
  showBreadcrumbs = true
  showDraftLabel = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showWordCount = false
  showZenMode = false

[list]
  showHero = false
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = false
  showCards = true
  cardView = true
  groupByYear = true

[taxonomy]
  showTermCount = true
  showBreadcrumbs = false
  cardView = true

[term]
  showBreadcrumbs = false
  groupByYear = false
  cardView = true
